### PR TITLE
"inverted" bullet buttons

### PR DESCRIPTION
**Pull request by csanner**
I'm not completely happy with how they turned out but I wanted to be able to do something specific with one layout...
I'd love to have a better way of moving the text around but the flex model doesn't seem to allow for that here.

Screenshot 2023-01-18 114136

### CODE REVIEW

**Comment by th3jesta** [comment]
Is this just to change the side of the button the text is on? I can see why you had trouble; that was a bear.

**Comment by csanner** [comment]
it's to flip the button around entirely - so that the "button" part is on the rounded end.
I wanted to be able to have two buttons on the same row and have them butting up against each other, but with the "button"-looking part on the outside. 
Screenshot_20230120_122225

I wanted the text to continue to follow the same layout as on the other buttons

**Comment by th3jesta** [comment]
Hmm, I could have sworn you already submitted a PR for that. Maybe someone else did. Either way, I think it's already implemented? https://github.com/th3jesta/ha-lcars/blob/master/README.md#:~:text=button%2Dlozenge%20button%2Dlozenge%2Dright

**Comment by th3jesta** [comment]
OH
I get it now.

**Comment by th3jesta** [comment]
I'll be releasing this in a few minutes. 
image

**Comment by csanner** [comment]
Awesome!

**Comment by th3jesta** [comment]
I'm going to go ahead and close this. Thanks for the idea! I built them based on the original lozenge, just squared off one side of the lozenge and adjusted the padding.

**Comment by csanner** [comment]
😂 that would have been much easier.
Thanks!

**Pull request closed without merging**
